[project]
name = "mcp_network"
version = "0.1.0"
description = "mcp_network"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.12.4",
    "requests",
    "colorlog",
    "apscheduler"
]
